### ISSUE TITLE
CRAN packages using GNUisms in Fortran

### ISSUE THREAD

**Issue by frajaroco** [stpp-GitHub-community/stpp#4]
Dear colleagues,

Please look at the below message from CRAN team with respect to your package. Basically, the problem arises with the compilation of the FORTRAN files in the Solaris (operating system).

Any suggestions?
---------------------------------------------------------------------------

On 24/12/2017 10:46, Prof Brian Ripley wrote:
> This concerns packages
> 
> CoSeg DMMF MethyBayes crimCV kexpmv norm2 optmatch rexpokit stpp
> 
> The CRAN policy says
> 
> 'Package authors should make all reasonable efforts to provide 
> cross-platform portable code.'
> 
> but these packages seem to compile only with gfortran.  See

Sorry, this URL vanished from the message before sending:

https://www.stats.ox.ac.uk/pub/bdr/flang/

> for logs of attempted installation with 'flang', the upcoming Fortran 
> front end for clang.  But many other Fortran compilers without GNU 
> extensions are available ....

And DMMF MethyBayes stpp already have failures with the Oracle compiler 
on their CRAN results pages.

> The R manual did warn you about the use of GNU extensions such as isnan, 
> dgamma, dlgama and realpart.  (For dgamma and dlgama you can use 
> wrappers for the C functions provided by R: see §6.7.2 of the manual, 
> and you can also find Fortran substitutes by a web search.  Fortran 2008 
> cannot be assumed.)
> 
> Please submit a corrected update before Jan 31 to safely retain the 
> package on CRAN.
> 
> (We appreciate that you will probably not be able to reproduce these 
> errors, but the logs should suffice to pinpoint the issues in 
> conjunction with the Fortran standards linked from 
> https://developer.r-project.org/Portability.html.)
>

**Comment by barryrowlingson** [comment]
The log file seems to imply the only problem is the use of GNU fortran's built in dgamma function. This is only called from `circ.f` in `stpp`, and that file contains a function definition called `GAMMAX` which isn't called anywhere in the code. A quick test shows it seems to return the same values as GNU `dgamma`. Perhaps we can just replace `dgamma` with `dgammax`, although the code contains the dreaded phrase "machine dependent parameters"...

Another solution is to call R's C interface to `gammafn`.

To do this portably from Fortran requires (I think) a C interface module:

```
#include <R.h>
#include <Rmath.h>
void F77_SUB(dgammafn)(double* x, double *y) {
  *y = gammafn(*x);
}
```

and then called from Fortran with the return value passed by reference in the second parameter rather than returned as a function call (there's a note in Writing R Extensions that mentions this):
 
```
      x = 1.2
      y = 0.0
      call dgammafn(x,y)
      print *,y
```

**Comment by frajaroco** [comment]
Many thanks Barry, you suggestions was really useful I think that the problem is fixed. This afternoon Edith has submitted our package in the CRAN. 

Best!
