### ISSUE TITLE
Error when installing: ‘stpp’ is not available (for R version 3.4.3) 

### ISSUE THREAD

**Issue by lbraun** [stpp-GitHub-community/stpp#5]
Hi! I need to install stpp for a class but I'm getting the following message when I try to install it:
```
Warning message:
package ‘stpp’ is not available (for R version 3.4.3) 
```

Is stpp not compatible with my version of R? Or is the package just not available?

Thanks for your help.
Lucas

**Comment by barryrowlingson** [comment]
stpp was removed from CRAN because of warnings with some operating systems. 

You may be able to install from the MRAN time machine, which takes snapshots of CRAN as it was on a given date. To do this, set the CRAN repos option to a recent date:

Starting with an R and not being able to install `stpp`:
```
> library(stpp)
Error in library(stpp) : there is no package called ‘stpp’
> install.packages("stpp")
Warning message:
package ‘stpp’ is not available (for R version 3.4.2) 
> options()$repos
                      CRAN 
"http://cran.rstudio.com/" 
```

I change the repository:

```
> options(repos="https://mran.microsoft.com/snapshot/2018-01-31")
> install.packages("stpp")
trying URL 'https://mran.microsoft.com/snapshot/2018-01-01/src/contrib/stpp_2.0-2.tar.gz'
Content type 'application/octet-stream' length 821352 bytes (802 KB)
```

and it seems to work. Note you'll also be pointing at old versions of all the CRAN packages, so this might get you out of a spot. Jan 31 was the last snapshot that had `stpp` in it.

**Comment by lbraun** [comment]
Ok, thanks so much for your quick response. Our professor said we actually don't need it quite yet, so I will wait and see if there is a fix in place next week.

**Comment by frajaroco** [comment]
Hi lbraun, stpp package is now available in CRAN, so install and enjoy it!
