### ISSUE TITLE
`stpp` package issue relates with R-panel on shiny io apps

### ISSUE THREAD

**Issue by jerrytohvan** [stpp-GitHub-community/stpp#6]
Hi everyone, need your help resolving issue regarding the use of stpp package on shiny io apps. My codes works normally on local computer but i encountered a deployment issue relates to rpanel v1.1-4 to the shiny io.

It starts failing after ` building: Building package: rpanel`

My local env is running on R version 3.5.3 on windows.

![image](https://user-images.githubusercontent.com/12148853/55611103-658cf600-5739-11e9-8256-45d1aa1732c8.png)

heres a screenshot

**Comment by barryrowlingson** [comment]
When you say "the shiny io" do you mean you are trying to deploy and run this on the https://www.shinyapps.io/ server run by RStudio?

If so then it would be an issue with `rpanel` rather than anything to do with `stpp`. Have you tried asking RStudio Shinyapps.io support?

`rpanel` is a package for making desktop GUI interfaces and so it has little utility from a server-based R such as shiny. But that doesn't mean it can't be installed on a server - just as long as the functions in it aren't called.
